### ISSUE TITLE
question about aes mode selection.

### ISSUE THREAD

**Issue by RMheng** [0x01h/cryptemis#1]
Thanks for your sharing! It seems that you use aes-cfb. I’m doubt that why don’t you choose aes-gcm? gcm has been proved to be more secure than cfb. And now the module Cipher has been supported for gcm.Looking for your reply!

**Comment by 0x01h** [comment]
Hello,

Is there any research paper for comparison of CFB and GCM?

Thanks!

**Comment by RMheng** [comment]
Thanks for your reply. Firstly, I should apology for my assertion that 

> gcm has been proved to be more secure than cfb

Each mode has its Appropriate range of use. And I didn't read any research paper for the comparsion of the two. 

I thought GCM is more secure because it has  authentication function. And this answer ——[Please consider long and hard if you can't get around implementing your own cryptography](https://stackoverflow.com/questions/1220751/how-to-choose-an-aes-encryption-mode-cbc-ecb-ctr-ocb-cfb) He conclue eight mode and recommend GCM at last.

Have you ever considered that set an option to give the user a chance to choose the mode they want?

Actually, I git clone the code and alter the MODE_CFB to MODE_GCM in [there](https://github.com/0x01h/cryptemis/blob/efde04d37d0d74d52901047937a107de6c2ffd4d/cryptemis/cryptemis.py#L27), got the expected result too.

Thanks for your reply!

**Comment by 0x01h** [comment]
It's not a future plan, but you may create a pull request.

**Comment by RMheng** [comment]
ok. 
Thanks!
